[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/pressly/lg"
  version = "1.1.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/brave-intl/bat-go"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"
